development: &development
  adapter: postgresql
  encoding: unicode
  database: kuestions_development
  pool: 5
  username: kre
  password:


test: &test
  <<: *development
  database: kuestions_test

staging:
  <<: *development
  database: kuestions_staging

production:
  <<: *development
  database: kuestions_production