development: &development
  adapter: mysql2
  database: kuestions_development
  host: localhost
  user: root
  pool: 5
  timeout: 5000


test: &test
  <<: *development
  database: kuestions_test

staging:
  <<: *development
  database: kuestions_staging

production:
  <<: *development
  database: kuestions_production